// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';

export function CreateNotifierConfig(arg1:models.NotifierConfig):Promise<void>;

export function CreateScript(arg1:models.Script):Promise<void>;

export function CreateTask(arg1:models.Task):Promise<void>;

export function DeleteEnvironmentVariable(arg1:string):Promise<void>;

export function DeleteNotifierConfig(arg1:string):Promise<void>;

export function DeleteScript(arg1:string):Promise<void>;

export function DeleteTask(arg1:string):Promise<void>;

export function GetAllLogs(arg1:number):Promise<Array<models.TaskLog>>;

export function GetAllNotifierConfigs():Promise<Array<models.NotifierConfig>>;

export function GetAllScripts():Promise<Array<models.Script>>;

export function GetAllTasks():Promise<Array<models.Task>>;

export function GetDependencies():Promise<Array<main.Dependency>>;

export function GetEnvironmentVariables():Promise<Record<string, string>>;

export function GetScript(arg1:string):Promise<models.Script>;

export function GetScriptsDir():Promise<string>;

export function GetStats():Promise<Record<string, any>>;

export function GetTask(arg1:string):Promise<models.Task>;

export function GetTaskLogs(arg1:string,arg2:number):Promise<Array<models.TaskLog>>;

export function InstallDependency(arg1:string,arg2:string):Promise<void>;

export function OpenDirectory(arg1:string):Promise<void>;

export function RunScript(arg1:string,arg2:boolean):Promise<void>;

export function RunTaskNow(arg1:string):Promise<void>;

export function SelectFile():Promise<string>;

export function SetEnvironmentVariable(arg1:string,arg2:string):Promise<void>;

export function ToggleTaskStatus(arg1:string):Promise<void>;

export function UninstallDependency(arg1:string,arg2:string):Promise<void>;

export function UpdateNotifierConfig(arg1:models.NotifierConfig):Promise<void>;

export function UpdateScript(arg1:models.Script):Promise<void>;

export function UpdateTask(arg1:models.Task):Promise<void>;

export function ValidateCron(arg1:string):Promise<boolean>;
