// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNotifierConfig(arg1) {
  return window['go']['main']['App']['CreateNotifierConfig'](arg1);
}

export function CreateScript(arg1) {
  return window['go']['main']['App']['CreateScript'](arg1);
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function DeleteEnvironmentVariable(arg1) {
  return window['go']['main']['App']['DeleteEnvironmentVariable'](arg1);
}

export function DeleteNotifierConfig(arg1) {
  return window['go']['main']['App']['DeleteNotifierConfig'](arg1);
}

export function DeleteScript(arg1) {
  return window['go']['main']['App']['DeleteScript'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetAllLogs(arg1) {
  return window['go']['main']['App']['GetAllLogs'](arg1);
}

export function GetAllNotifierConfigs() {
  return window['go']['main']['App']['GetAllNotifierConfigs']();
}

export function GetAllScripts() {
  return window['go']['main']['App']['GetAllScripts']();
}

export function GetAllTasks() {
  return window['go']['main']['App']['GetAllTasks']();
}

export function GetDependencies() {
  return window['go']['main']['App']['GetDependencies']();
}

export function GetEnvironmentVariables() {
  return window['go']['main']['App']['GetEnvironmentVariables']();
}

export function GetScript(arg1) {
  return window['go']['main']['App']['GetScript'](arg1);
}

export function GetScriptsDir() {
  return window['go']['main']['App']['GetScriptsDir']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function GetTaskLogs(arg1, arg2) {
  return window['go']['main']['App']['GetTaskLogs'](arg1, arg2);
}

export function InstallDependency(arg1, arg2) {
  return window['go']['main']['App']['InstallDependency'](arg1, arg2);
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function RunScript(arg1, arg2) {
  return window['go']['main']['App']['RunScript'](arg1, arg2);
}

export function RunTaskNow(arg1) {
  return window['go']['main']['App']['RunTaskNow'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SetEnvironmentVariable(arg1, arg2) {
  return window['go']['main']['App']['SetEnvironmentVariable'](arg1, arg2);
}

export function ToggleTaskStatus(arg1) {
  return window['go']['main']['App']['ToggleTaskStatus'](arg1);
}

export function UninstallDependency(arg1, arg2) {
  return window['go']['main']['App']['UninstallDependency'](arg1, arg2);
}

export function UpdateNotifierConfig(arg1) {
  return window['go']['main']['App']['UpdateNotifierConfig'](arg1);
}

export function UpdateScript(arg1) {
  return window['go']['main']['App']['UpdateScript'](arg1);
}

export function UpdateTask(arg1) {
  return window['go']['main']['App']['UpdateTask'](arg1);
}

export function ValidateCron(arg1) {
  return window['go']['main']['App']['ValidateCron'](arg1);
}
